version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=deliveries
    ports:
      - "3006:3006"
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - db
    build: ./
    ports:
      - "3000:3000"
    restart: on-failure
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=deliveries
      - DB_PORT=3306

volumes: 
  db:
